server:
   port: 8080
   
spring:
   application:
      name: UserManagementApp
   datasource:
      url: jdbc:mariadb://localhost:3300/userdb_01
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 123456
      
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MariaDBDialect
  
      database-plataform: org.hibernate.dialect.MariaDB102Dialect
      show-sql: true
      
services:
   email:
      url: http://localhost:8090/
      endpoints:
         sendEmail: api/v1/generateValidationLink