server:
   port: 8090

spring:
  application:
      name: EmailVerificationApp
  mail:
      host: smtp.gmail.com
      port: 587
      username: buscar.catcharide@gmail.com
      password: beplzmzrymqmlzte
      properties:
        mail:          
          smtp:  
            auth: true
            starttls:
              enable: true
              required: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
  redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
               
secrets:
    name: Buscar-Catch-A-Ride
    baseUrl: http://localhost:8090/api/v1/validate
  